call getj CurData
call getj CurDepth
call getj CurDepthNotes
call getj CurDepthQuality
call getj CurMooring
call getj CurPlanam
call getj CurWatphy
call getj EdmClient
call getj EdmInstrument
call getj LogMrnLoads
call getj LogSessions
call getj LogUsers
call getj LogVosLoads
call getj MrnConstituent
call getj MrnCountry
call getj MrnInstitutes
call getj MrnInventory
call getj MrnInvestigators
call getj MrnInvStats
call getj MrnPlanam
call getj MrnPositions
call getj MrnSamples
call getj MrnSedphy
call getj MrnSedpol1
call getj MrnSedpol2
call getj MrnSfriGrid
call getj MrnStation
call getj MrnSurvey
call getj MrnSurveyConstituent
call getj MrnSurveyNotes
call getj MrnTisanimal
call getj MrnTisanpart
call getj MrnTisphy
call getj MrnTispol1
call getj MrnTispol2
call getj MrnWatchem1
call getj MrnWatchem2
call getj MrnWatchl
call getj MrnWatcurrents
call getj MrnWatnut
call getj MrnWatphy
call getj MrnWatpol1
call getj MrnWatpol2
call getj MrnWeather
call getj MrnZonesCovered
call getj SadUserDset
call getj SadUsers
call getj VosArch
call getj VosArch2
call getj VosMain
call getj VosMain2
call getj VosReject
call getj VosTable
call getj WetData
call getj WetPeriod
call getj WetPeriodNotes
call getj WetStation
pause