call putj CurData
call putj CurDepth
call putj CurDepthNotes
call putj CurDepthQuality
call putj CurMooring
call putj CurPlanam
call putj CurWatphy
call putj EdmClient
call putj EdmInstrument
call putj LogMrnLoads
call putj LogSessions
call putj LogUsers
call putj LogVosLoads
call putj MrnConstituent
call putj MrnCountry
call putj MrnInstitutes
call putj MrnInventory
call putj MrnInvestigators
call putj MrnInvStats
call putj MrnPlanam
call putj MrnPositions
call putj MrnSamples
call putj MrnSedphy
call putj MrnSedpol1
call putj MrnSedpol2
call putj MrnSfriGrid
call putj MrnStation
call putj MrnSurvey
call putj MrnSurveyConstituent
call putj MrnSurveyNotes
call putj MrnTisanimal
call putj MrnTisanpart
call putj MrnTisphy
call putj MrnTispol1
call putj MrnTispol2
call putj MrnWatchem1
call putj MrnWatchem2
call putj MrnWatchl
call putj MrnWatcurrents
call putj MrnWatnut
call putj MrnWatphy
call putj MrnWatpol1
call putj MrnWatpol2
call putj MrnWeather
call putj MrnZonesCovered
call putj SadUserDset
call putj SadUsers
call putj VosArch
call putj VosArch2
call putj VosMain
call putj VosMain2
call putj VosReject
call putj VosTable
call putj WetData
call putj WetPeriod
call putj WetPeriodNotes
call putj WetStation
pause