set JAVAC="C:\Program Files\Java\j2sdk1.4.1_02\bin\javac"

%JAVAC% AddClientFrame.java
%JAVAC% AddInstrumentFrame.java
%JAVAC% AdminCalcSpeeds.java
%JAVAC% AdminChangeSubdes.java
%JAVAC% AdminCheckDupStations.java
%JAVAC% AdminCheckStations.java
%JAVAC% AdminDelInv.java
%JAVAC% AdminDelStation.java
%JAVAC% AdminDisplStation.java
%JAVAC% AdminDisplStationId.java
%JAVAC% AdminSplitCurDepth.java
%JAVAC% AdminUpdateCurDepthParms.java
%JAVAC% AdminUpdateInvStats.java
%JAVAC% AdminUpdateInvStats_old.java
%JAVAC% AdminWetPeriodUpd.java
%JAVAC% CheckMainReject.java
%JAVAC% CheckMainReject2.java
%JAVAC% CheckRemoveWETDataFrame.java
%JAVAC% CheckVOSData.java
%JAVAC% CheckVOSData2.java
%JAVAC% ConfirmRemoveWETDataFrame.java
%JAVAC% ConfirmStationsFrame.java
%JAVAC% CountRecs.java
%JAVAC% CurData.java
%JAVAC% CurDepth.java
%JAVAC% CurDepthNotes.java
%JAVAC% CurDepthQc.java
%JAVAC% CurDepthQcParmcodes.java
%JAVAC% CurDepthQuality.java
%JAVAC% CurMooring.java
%JAVAC% CurPlanam.java
%JAVAC% CurWatphy.java
%JAVAC% EdmClient.java
%JAVAC% EdmClient2.java
%JAVAC% EdmInstrument.java
%JAVAC% EdmInstrument2.java
%JAVAC% ExtractCURAllDepthsData.java
%JAVAC% ExtractCURData.java
%JAVAC% ExtractCURDepthsData.java
%JAVAC% ExtractCURFrame.java
%JAVAC% ExtractCURSelectFrame.java
%JAVAC% ExtractMRNCurData.java
%JAVAC% ExtractMRNFrame.java
%JAVAC% ExtractMRNPhysNutData.java
%JAVAC% ExtractMRNPhysNutDataODV.java
%JAVAC% ExtractMRNPhysNutDataPedro.java
%JAVAC% ExtractMRNPhysNutDataTest.java
%JAVAC% ExtractMRNSedChmData.java
%JAVAC% ExtractMRNSedPhyData.java
%JAVAC% ExtractMRNSedPolData.java
%JAVAC% ExtractMRNSelectFrame.java
%JAVAC% ExtractMRNStationData.java
%JAVAC% ExtractMRNTisPolData.java
%JAVAC% ExtractMRNWatChmData.java
%JAVAC% ExtractMRNWatPolData.java
%JAVAC% ExtractProgressFrame.java
%JAVAC% ExtractVOSData.java
%JAVAC% ExtractVOSFrame.java
%JAVAC% ExtractWAVData.java
%JAVAC% ExtractWAVFrame.java
%JAVAC% ExtractWETData.java
%JAVAC% ExtractWETData2.java
%JAVAC% ExtractWETFrame.java
%JAVAC% LoadCLIWOCData.java
%JAVAC% LoadMRNCommon.java
%JAVAC% LoadMRNCommon_old.java
%JAVAC% LoadMRNCurData.java
%JAVAC% LoadMRNCurFrame.java
%JAVAC% LoadMRNLogDetailFrame.java
%JAVAC% LoadMRNLogListFrame.java
%JAVAC% LoadMRNProgressFrame.java
%JAVAC% LoadMRNReports.java
%JAVAC% LoadMRNReportsFrame.java
%JAVAC% LoadMRNSedData.java
%JAVAC% LoadMRNSedFrame.java
%JAVAC% LoadMRNSelectFileFrame.java
%JAVAC% LoadMRNWatData.java
%JAVAC% LoadMRNWatFrame.java
%JAVAC% LoadVOSData.java
%JAVAC% LoadVOSData2.java
%JAVAC% LoadVOSDataUpd.java
%JAVAC% LoadVOSFrame.java
%JAVAC% LoadVOSLogListFrame.java
%JAVAC% LoadVOSProgressFrame.java
%JAVAC% LoadVOSReject.java
%JAVAC% LoadVOSRemoveDataFrame.java
%JAVAC% LoadVOSSelectFileFrame.java
%JAVAC% LoadWETDataFrame.java
%JAVAC% LoginConfirmFrame.java
%JAVAC% LoginFrame.java
%JAVAC% LogMrnLoads.java
%JAVAC% LogSessions.java
%JAVAC% LogUsers.java
%JAVAC% LogVosLoads.java
%JAVAC% MaintainStationsFrame.java
%JAVAC% MrnConstituent.java
%JAVAC% MrnCountry.java
%JAVAC% MrnCurrents.java
%JAVAC% MrnEtopo.java
%JAVAC% MrnEtopo2.java
%JAVAC% MrnInstitutes.java
%JAVAC% MrnInvestigators.java
%JAVAC% MrnInvStats.java
%JAVAC% MrnPlachl.java
%JAVAC% MrnPlanam.java
%JAVAC% MrnPlapes.java
%JAVAC% MrnPlaphy.java
%JAVAC% MrnPlapol1.java
%JAVAC% MrnPlapol2.java
%JAVAC% MrnPlatax.java
%JAVAC% MrnPositions.java
%JAVAC% MrnQcBroadChecks.java
%JAVAC% MrnQcRangeAreaMask.java
%JAVAC% MrnQcSdMultiplier.java
%JAVAC% MrnSamples.java
%JAVAC% MrnScientists.java
%JAVAC% MrnSedchem1.java
%JAVAC% MrnSedchem2.java
%JAVAC% MrnSedpes.java
%JAVAC% MrnSedphy.java
%JAVAC% MrnSedpol1.java
%JAVAC% MrnSedpol2.java
%JAVAC% MrnSedtax.java
%JAVAC% MrnSfriGrid.java
%JAVAC% MrnStation.java
%JAVAC% MrnSurvey.java
%JAVAC% MrnSurveyConstituent.java
%JAVAC% MrnSurveyNotes.java
%JAVAC% MrnSurveyType.java
%JAVAC% MrnTisanimal.java
%JAVAC% MrnTisanpart.java
%JAVAC% MrnTispes.java
%JAVAC% MrnTisphy.java
%JAVAC% MrnTispol1.java
%JAVAC% MrnTispol2.java
%JAVAC% MrnWatchem1.java
%JAVAC% MrnWatchem2.java
%JAVAC% MrnWatchl.java
%JAVAC% MrnWatcurrents.java
%JAVAC% MrnWatnut.java
%JAVAC% MrnWatphy.java
%JAVAC% MrnWatpol1.java
%JAVAC% MrnWatpol2.java
%JAVAC% MrnWatprofqc.java
%JAVAC% MrnWatqc.java
%JAVAC% MrnWeather.java
%JAVAC% MrnWoatlas5.java
%JAVAC% MrnZonesCovered.java
%JAVAC% PreLoadMRNCurFrame.java
%JAVAC% PreLoadMRNSedFrame.java
%JAVAC% PreLoadMRNWatFrame.java
%JAVAC% PreLoadWETDataFrame.java
%JAVAC% ProductMRNFrame.java
%JAVAC% ProductMRNGetFileFrame.java
%JAVAC% ProductMRNGetParmsFrame.java
%JAVAC% ProductProgressFrame.java
%JAVAC% ProductVOSFrame.java
%JAVAC% ProductVOSGetFileFrame.java
%JAVAC% ProductVOSGetParmsFrame.java
%JAVAC% SadConstants.java
%JAVAC% SadUserDset.java
%JAVAC% SadUserQueue.java
%JAVAC% SadUsers.java
%JAVAC% SelectWETLoadFileFrame.java
%JAVAC% Tables.java
%JAVAC% TestNumbers.java
%JAVAC% UserConfirmFrame.java
%JAVAC% UserDeleteFrame.java
%JAVAC% UserFrame.java
%JAVAC% UserLogListFrame.java
%JAVAC% UserSelectFrame.java
%JAVAC% UserTimeoutFrame.java
%JAVAC% VosArch.java
%JAVAC% VosArch2.java
%JAVAC% VosMain.java
%JAVAC% VosMain2.java
%JAVAC% VosReject.java
%JAVAC% VosTable.java
%JAVAC% WavData.java
%JAVAC% WavInstStats.java
%JAVAC% WavPeriod.java
%JAVAC% WavSponsor.java
%JAVAC% WavStation.java
%JAVAC% WetData.java
%JAVAC% WetPeriod.java
%JAVAC% WetPeriodCounts.java
%JAVAC% WetPeriodNotes.java
%JAVAC% WetStation.java
